include:
- access_management_pkg/*
kind: ArchiveUploadSpec
name: access-management-pkg-7wCV

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: access-management-producer-55d7f7d3-7a29-4c0c-a978-c6201ef01771
spec:
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://access-management-pkg-7wCV
status:
  buildstatus: pending
  lastUpdateTimestamp: "2025-05-06T05:19:16Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: access-management-producer
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: access_management.main.main
    packageref:
      name: access-management-producer-55d7f7d3-7a29-4c0c-a978-c6201ef01771
      namespace: ""
  requestsPerPod: 1
  resources: {}
